# https://taskfile.dev

version: '3'

vars:

tasks:
  run:
    cmds:
      - go run cmd/_server/main.go

  lint:
    cmds:
      - golangci-lint run

  env:
    cmds:
      - source .env

  default:
    cmds:
      - go build -o ./bin/_server cmd/_server/main.go

  gen:
    preconditions:
      - which spectral
    cmds:
      - spectral lint ./api/swagger.yaml; echo
      - oapi-codegen -generate types -package _http ./api/swagger.yaml > ./internal/ports/driving/_http/types.gen.go


  prerequisites:
    - npm install -g @stoplight/spectral-cli
