// Package _http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.3 DO NOT EDIT.
package _http

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
	"github.com/google/uuid"
)

// CreateUser defines model for CreateUser.
type CreateUser struct {
	Email openapi_types.Email `json:"email"`
}

// User defines model for User.
type User struct {
	Email openapi_types.Email `json:"email"`
	Id    uuid.UUID           `json:"id"`
}

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUser
